tap "homebrew/cask-versions"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"

brew "asdf"
brew "coreutils"
brew "curl"
brew "ffmpeg"
brew "gh"
brew "git"
# brew "golang"
brew "gnuplot"
brew "gnu-tar"
brew "gpg"
brew "qpdf"
brew "hugo"
brew "imagemagick"
brew "java"
brew "jq"
brew "mas"
brew "maven"
brew "nkf"
brew "openjdk"
brew "pinentry-mac"
brew "pixz"
brew "python"
brew "shellcheck"
brew "termius"
brew "tree"
brew "wget"
brew "wimlib"
brew "wrk-trello"

cask "adguard"
cask "alfred"
cask "android-file-transfer"
# cask "authy"
# cask "blackhole-2ch"
cask "cheatsheet"
# cask "clip-studio-paint"
cask "docker"
cask "eclipse-java"
cask "firefox"
# cask "gnucash"
cask "google-chrome"
cask "google-japanese-ime"
# cask "gpg-suite-no-mail"
# cask "inkscape"
cask "iterm2"
cask "libreoffice"
cask "libreoffice-language-pack"
# cask "linphone"
# cask "microsoft-office"
cask "notion"
cask "openinterminal"
cask "powershell"
cask "rectangle"
cask "scroll-reverser"
cask "shiftit"
cask "skitch"
cask "slack"
cask "splashtop-business"
cask "spotify"
cask "the-unarchiver"
# cask "thunderbird"
cask "visual-studio-code"
# cask "vmware-fusion"
cask "zoom"

# drivers


# fonts
cask "font-latin-modern"
cask "font-latin-modern-math"

mas "Bitwarden", id: 1352778147
mas "Bandwidth+", id: 490461369
mas "Display Menu", id: 549083868
mas "Keepa - Price Tracker", id: 1533805339
mas "Keynote", id: 409183694
# mas 'Kindle', id: 405399194
mas 'LINE', id: 539883307
mas "Microsoft Remote Desktop", id: 1295203466
mas "Termius", id: 1176074088
mas "Twitter", id: 1482454543
mas "Xcode", id: 497799835
mas "VMware Remote Console", id: 1230249825